export const NUMBER_OF_ROLLS: number = 3;
export const NUMBER_OF_DICE: number = 5;
export const LOWER_TOTAL: number = 63;
export const LOWER_BONUS: number = 35;

import { ComboItem } from "../components/combination/combo";
export const BOARD: ComboItem[] = [
  {
    id: 'one',
    label: '1',
    score: null,
    played: false,
    value: 1,
    bonus: false,
    description: 'one',
  },
  {
    id: 'two',
    label: '2',
    score: null,
    played: false,
    value: 2,
    bonus: false,
    description: 'two',
  },
  {
    id: 'three',
    label: '3',
    score: null,
    played: false,
    value: 3,
    bonus: false,
    description: 'three',
  },
  {
    id: 'four',
    label: '4',
    score: null,
    played: false,
    value: 4,
    bonus: false,
    description: 'four',
  },
  {
    id: 'five',
    label: '5',
    score: null,
    played: false,
    value: 5,bonus: false,
    description: 'five',
  },
  {
    id: 'six',
    label: '6',
    score: null,
    played: false,
    value: 6,
    bonus: false,
    description: 'six',
  },
  {
    id: 'three-kind',
    label: '3x',
    score: null,
    played: false,
    bonus: false,
    description: 'three of a kind',
  },
  {
    id: 'four-kind',
    label: '4x',
    score: null,
    played: false,
    bonus: false,
    description: 'four of a kind',
  },
  {
    id: 'fh',
    label: 'full house',
    score: null,
    played: false,
    bonus: false,
    description: 'full house',
  },
  {
    id: 'sm-st',
    label: 'small straight',
    score: null,
    played: false,
    bonus: false,
    description: 'small straight',
  },
  {
    id: 'lg-st',
    label: 'large straight',
    score: null,
    played: false,
    bonus: false,
    description: 'large straight',
  },
  {
    id: 'benzee',
    label: 'benzee',
    score: null,
    played: false,
    bonus: false,
    description: 'benzee',
  },
  {
    id: 'chance',
    label: '?',
    score: null,
    played: false,
    bonus: false,
    description: 'chance',
  },
];

export const KONAMI = [
  'ArrowUp',
  'ArrowUp',
  'ArrowDown',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'ArrowLeft',
  'ArrowRight',
  'b',
  'a',
  'Enter',
];
