/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DieItem } from "./components/die/die";
export namespace Components {
    interface AppBoard {
    }
    interface AppDie {
        "die": DieItem;
        "locked": boolean;
        "position": number;
    }
    interface AppRoot {
    }
    interface AppScore {
        "disabled": boolean;
        "label": string;
        "position": number;
        "score": number;
    }
}
declare global {
    interface HTMLAppBoardElement extends Components.AppBoard, HTMLStencilElement {
    }
    var HTMLAppBoardElement: {
        prototype: HTMLAppBoardElement;
        new (): HTMLAppBoardElement;
    };
    interface HTMLAppDieElement extends Components.AppDie, HTMLStencilElement {
    }
    var HTMLAppDieElement: {
        prototype: HTMLAppDieElement;
        new (): HTMLAppDieElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppScoreElement extends Components.AppScore, HTMLStencilElement {
    }
    var HTMLAppScoreElement: {
        prototype: HTMLAppScoreElement;
        new (): HTMLAppScoreElement;
    };
    interface HTMLElementTagNameMap {
        "app-board": HTMLAppBoardElement;
        "app-die": HTMLAppDieElement;
        "app-root": HTMLAppRootElement;
        "app-score": HTMLAppScoreElement;
    }
}
declare namespace LocalJSX {
    interface AppBoard {
    }
    interface AppDie {
        "die"?: DieItem;
        "locked"?: boolean;
        "position"?: number;
    }
    interface AppRoot {
    }
    interface AppScore {
        "disabled"?: boolean;
        "label"?: string;
        "onSelectScore"?: (event: CustomEvent<boolean>) => void;
        "position"?: number;
        "score"?: number;
    }
    interface IntrinsicElements {
        "app-board": AppBoard;
        "app-die": AppDie;
        "app-root": AppRoot;
        "app-score": AppScore;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-board": LocalJSX.AppBoard & JSXBase.HTMLAttributes<HTMLAppBoardElement>;
            "app-die": LocalJSX.AppDie & JSXBase.HTMLAttributes<HTMLAppDieElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-score": LocalJSX.AppScore & JSXBase.HTMLAttributes<HTMLAppScoreElement>;
        }
    }
}
